<!doctype html>
<html lang="es">

<head>
    <!-- // Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Required meta tags // -->

    <meta name="description"
        content="Login and Register Form HTML Template - developed by 'ceosdesigns' - sold exclusively on 'themeforest.net'">
    <meta name="author" content="ceosdesigns.sk">

    <title>ERP</title>

    <!-- // Favicon -->
    <link href="{{ asset('login/images/favicon.png') }}" rel="icon">
    <!-- Favicon // -->

    <!-- // Google Web Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&amp;display=swap" rel="stylesheet">
    <!-- Google Web Fonts // -->

    <!-- // Font Awesome 5 Free -->
    <link href="{{ asset('login/css/all.css') }}" crossorigin="anonymous" rel="stylesheet">
    <!-- Font Awesome 5 Free // -->

    <!-- // Template CSS files -->
    <link href="{{ asset('login/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('login/css/styles.css') }}" rel="stylesheet">
    <!-- Template CSS files  // -->
    <style type="text/css">
        @keyframes ldio-w6bds7bumam {
            0% {
                top: 96px;
                left: 96px;
                width: 0;
                height: 0;
                opacity: 1;
            }

            100% {
                top: 18px;
                left: 18px;
                width: 156px;
                height: 156px;
                opacity: 0;
            }
        }

        .ldio-w6bds7bumam div {
            position: absolute;
            border-width: 4px;
            border-style: solid;
            opacity: 1;
            border-radius: 50%;
            animation: ldio-w6bds7bumam 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
        }

        .ldio-w6bds7bumam div:nth-child(1) {
            border-color: #e90c59;
            animation-delay: 0s;
        }

        .ldio-w6bds7bumam div:nth-child(2) {
            border-color: #46dff0;
            animation-delay: -0.5s;
        }

        .loadingio-spinner-ripple-qgb15v4cf7r {
            width: 200px;
            height: 200px;
            display: inline-block;
            overflow: hidden;
            background: #ffffff00;
        }

        .ldio-w6bds7bumam {
            width: 100%;
            height: 100%;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0;
            /* see note above */
        }

        .ldio-w6bds7bumam div {
            box-sizing: content-box;
        }

        /* generated by https://loading.io/ */
    </style>
    <style>
        #loader-menor {
            position: fixed;
            top: 0;
            left: 0;
            z-index: 9999;
            width: 100%;
            height: 100%;
            background-color: #ffffff96;
            line-height: 100vh;
            text-align: center;
        }
    </style>
</head>

<body>
    <!-- // Preloader -->
    <div id="nm-preloader" class="nm-aic nm-vh-md-100">
        <div class="nm-ripple">
            <div></div>
            <div></div>
        </div>
    </div>
    <div style="display: none" id="loader-menor">
        <div class="loadingio-spinner-ripple-qgb15v4cf7r">
            <div class="ldio-w6bds7bumam">
                <div></div>
                <div></div>
            </div>
        </div>
    </div>
    <!-- Preloader // -->

    <main id="page-content" class="d-flex nm-aic nm-vh-md-100" style="position: relative;">
        <div class="overlay"></div>

        <div class="nm-tm-wr">
            <div class="container">
                <form class="login-form" method="POST" action="{{ route('inicio') }}">
                    @csrf
                    <div style="background: #ce383a47;" class="nm-hr nm-up-rl-3">
                        <img style="max-width: 100%;" src="{{ asset('login/logo_erp.png') }}">
                    </div>

                    <div class="input-group nm-gp">
                        <span class="nm-gp-pp"><i class="fas fa-user"></i></span>
                        <input name="usuario" type="text" class="form-control" id="inputUsername" tabindex="1"
                            placeholder="Usuario" required>
                    </div>

                    <div class="input-group nm-gp">
                        <span class="nm-gp-pp"><i class="fas fa-lock"></i></span>
                        <input name="password" type="password" class="form-control" id="inputPassword" tabindex="2"
                            placeholder="ContraseÃ±a" required>
                    </div>

                    <div class="input-group nm-gp">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="rememberMe">
                            <label class="form-check-label nm-check" for="rememberMe">Mantenme conectado</label>
                        </div>
                    </div>

                    <div class="row nm-aic nm-mb-1">
                        <div class="col-sm-6 nm-mb-1 nm-mb-sm-0">
                            <button id="submit" class="btn btn-primary nm-hvr nm-btn-2">Ingresar</button>
                        </div>

                        <div class="col-sm-6 nm-sm-tr">
                            <a class="nm-fs-1 nm-fw-bd" href="#">Â¿Has olvidado tu contraseÃ±a?</a>
                        </div>
                    </div>

                    <footer hidden
                        style="text-align: center; margin-top: 2rem; font-size: 0.75rem; color: #97a4af; font-weight: 400;">
                        Don't have an account? <a class="nm-fs-1 nm-fw-bd" style="font-size: 0.75rem;"
                            href="signup.html">Signup</a></footer>
                </form>
            </div>
        </div>
    </main>

    <!-- // Vendor JS files -->
    <script src="{{ asset('login/js/jquery-3.6.0.min.js') }}"></script>
    <script src="{{ asset('login/js/bootstrap.bundle.min.js') }}"></script>
    <!-- Vendor JS files // -->

    <!-- Template JS files // -->
    <script src="{{ asset('login/js/script.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        @if ($errors->has('usuario'))
            Swal.fire({
                icon: "error",
                title: "Credenciales Incorrectas",
                text: "Usuario o contraseña incorrectas.",
            });
        @endif
    </script>
</body>

</html>
